### movie index
GET http://localhost:3000/movies

### movie create

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Sandlot",
  "year": 1993,
  "plot": "A group of boys learn life lessons while playing baseball on a rundown field."
}

### movie show

GET http://localhost:3000/movies/2

### movie update

PATCH http://localhost:3000/movies/2
Content-Type: application/json

{
  "age": 48,
  "gender": "female",
  "movie_id": 7
}

### movie delete

DELETE http://localhost:3000/movies/11

### actor index

GET http://localhost:3000/actors

### actor create 

POST http://localhost:3000/actors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDM0MDg2NjF9.wBM6GUprPOcU-X6cp4DVQcBCATV-ngPArb-0Nxu4GCw

{
  "first_name": "Jason",
  "last_name": "Sudeikis",
  "known_for": "Ted Lasso",
  "age": 50,
  "movie_id": 3
}

### actor show

GET http://localhost:3000/actors/14

### actor update

PATCH http://localhost:3000/actors/12
Content-Type: application/json

{
  "age": 48,
  "gender": "female",
  "movie_id": 7,
}

### actor delete 

DELETE http://localhost:3000/actors/8

### Users create (signup)

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Isabel the dog",
  "email": "isabel@thedog.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)

POST http://localhost:3000/sessions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDM0MDg2NjF9.wBM6GUprPOcU-X6cp4DVQcBCATV-ngPArb-0Nxu4GCw

{
  "email": "meghan@scherzer.com",
  "password": "password"
}

### Movie genre create

POST http://localhost:3000/movie_genres
Content-Type: application/json

{
  "movie_id": 5,
  "genre_id": 2
}