### movie index
GET http://localhost:3000/movies

### movie create

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Sandlot",
  "year": 1993,
  "plot": "A group of boys learn life lessons while playing baseball on a rundown field."
}

### movie show

GET http://localhost:3000/movies/2

### movie update

PATCH http://localhost:3000/movies/2
Content-Type: application/json

{
  "age": 48,
  "gender": "female",
  "movie_id": 7
}

### movie delete

DELETE http://localhost:3000/movies/11

### actor index

GET http://localhost:3000/actors

### actor create 

POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Jason",
  "last_name": "Sudeikis",
  "known_for": "Ted Lasso",
}

### actor show

GET http://localhost:3000/actors/14

### actor update

PATCH http://localhost:3000/actors/12
Content-Type: application/json

{
  "age": 48,
  "gender": "female",
  "movie_id": 7,
}

### actor delete 

DELETE http://localhost:3000/actors/8

